# Latest base image
FROM python:3.9.5

# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /code

COPY pyproject.toml .

RUN python -m pip install --upgrade pip

RUN pip install .


#to COPY the remote file at working directory in container
COPY src/ .
# Now the structure looks like this '/code/src/main.py'


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./main.py"]